List="dpot astro fish sedov-pres blast2-pres eddy_velx_f4 yf17_pres yf17_temp bump_dense"
set -- $List

for i
do
    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    echo $i
    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    echo "original"
    ./run.sh -c zfp -i inputdata/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/$i.dat -t junk | egrep -h "time|compress"
    #echo "..........................................."
    echo "prefix"
    ./run.sh -c zfp -i inputdata/prefixSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/prefixSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "..........................................."
    echo "interval point"
    ./run.sh -c zfp -i inputdata/pointintervalSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/pointintervalSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "interval block"
    ./run.sh -c zfp -i inputdata/blockintervalSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/blockintervalSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "interval chunk"
    ./run.sh -c zfp -i inputdata/chunkintervalSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/chunkintervalSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "..........................................."
    echo "..........................................."
    echo "random point"
    ./run.sh -c zfp -i inputdata/pointrandomSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/pointrandomSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "random block"
    ./run.sh -c zfp -i inputdata/blockrandomSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/blockrandomSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
    echo "random chunk"
    ./run.sh -c zfp -i inputdata/chunkrandomSample/$i.dat -t junk | egrep -h "time|compress"
    ./run.sh -c sz -i inputdata/chunkrandomSample/$i.dat -t junk | egrep -h "time|compress"
    echo "..........................................."
done

